import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Open Sans - Default body font
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

// Have Heart - Brand script font
const haveHeart = localFont({
  src: "../public/fonts/HaveHeart.otf",
  variable: "--font-have-heart",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${haveHeart.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
